version: 2
updates:
  - package-ecosystem: "javascript"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees:
      - "higoralves"
    commit-message:
      prefix: "dependabot"
      include: "scope"
    reviewers:
      - "higoralves"
    target-branch: "main"
