name: CD - iOS Staging

on:
  push:
    branches: staging
    paths-ignore:
      - '*.md'

jobs:
  ios:
    runs-on: macos-latest
    timeout-minutes: 50
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Yarn Cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Pods Cache
        uses: actions/cache@v2
        id: pods-cache
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Install Pods
        if: steps.pods-cache.outputs.cache-hit != 'true'
        run: cd ios && pod install

      - name: Run tests
        run: yarn test:ci

      - name: Generate the SSH Key
        run: |
          echo "${{ secrets.SSH_KEY }}" > ssh_key.asc
          gpg -d --passphrase ${{ secrets.SSH_KEY_PASSWORD }} --batch ssh_key.asc > ssh_key
          chmod 600 ./ssh_key

      - name: Create a new Keychain
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'setup'
          skip-tracking: true

      - name: Build iOS and send to TestFlight
        uses: maierj/fastlane-action@v1.4.0
        env:
          LC_ALL: 'en_US.UTF-8'
          LANG: 'en_US.UTF-8'
          TEAM_ID: ${{ secrets.TEAM_ID }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ./ssh_key
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          SIGNING_IDENTITY: ${{ secrets.SIGNING_IDENTITY }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        with:
          lane: 'ios staging'
          skip-tracking: true
