name: CI - Unit/Component Tests

on:
  pull_request:
    branches: [main, beta, staging]
    paths-ignore:
      - '*.md'

jobs:
  ios:
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Yarn Cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Pods Cache
        uses: actions/cache@v2
        id: pods-cache
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Install Pods
        if: steps.pods-cache.outputs.cache-hit != 'true'
        run: cd ios && pod install

      - name: Run tests
        run: yarn test:ci
