name: Jest Tests
on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/**.{js,jsx}'
      - 'src/**.{ts,tsx}'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'src/**.{js,jsx}'
      - 'src/**.{ts,tsx}'
      - 'package.json'
      - 'yarn.lock'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true       
      - name: Install Npm Dependencies
        run: yarn install
      - name: Run jest with CI option
        run: yarn test:ci
